name: Release pull request opened     
on:
  pull_request:
    types:
      - opened
      - reopened 
    branches:
      - main
  status: {}
  
jobs:
  # build and test
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    # - run: flutter build ios --release --no-codesign
  automerge:
    runs-on: macos-latest
    needs: build
    steps:
      - name: automerge
      - uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge, release"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"
  tag:
    runs-on: macos-latest
    needs: automerge
    steps:
      - uses: actions/checkout@v2

      - name: Set output for getting branch name
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
               
      - name: Tag commit
      - uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.vars.outputs.short_ref }}"
